name: CI Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn test
      
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build distribution archives (all profile)
      run: mvn clean package -P all
      
    - name: Build distribution archives (stable profile)
      run: mvn clean package -P stable
      
    - name: Upload distribution archives (all profile)
      uses: actions/upload-artifact@v4
      with:
        name: jnode-all-distribution
        path: |
          jnode-assembly/target/jnode-*.zip
        retention-days: 30
        
    - name: Upload individual JAR files
      uses: actions/upload-artifact@v4
      with:
        name: jnode-jar-modules
        path: |
          **/target/*.jar
          !**/target/*-sources.jar
          !**/target/*-javadoc.jar
          !**/target/original-*.jar
        retention-days: 30
        
    # Note: This CI workflow only builds and tests
    # Use the separate deploy.yml workflow for manual deployment