name: Create Deployment Artifacts

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release with artifacts'
        required: true
        default: false
        type: boolean
      release_tag:
        description: 'Release tag (e.g., v2.0.1)'
        required: false
        type: string

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build distribution archives
      run: mvn clean package -P all
      
    - name: Create lib-only artifacts with different H2 versions
      run: |
        mkdir -p artifacts
        cd jnode-assembly/target
        
        # Create base lib directory
        unzip -j jnode-*.zip "jnode/lib/*" -d ../../temp-lib/
        
        # Create artifact with H2 2.3.232 (latest)
        cp -r ../../temp-lib ../../artifacts/lib-h2-2.3.232
        rm -f ../../artifacts/lib-h2-2.3.232/h2-*.jar
        cp ../../jdbc-drivers/h2-2.3.232.jar ../../artifacts/lib-h2-2.3.232/
        cd ../../artifacts && tar -czf jnode-lib-h2-2.3.232.tar.gz lib-h2-2.3.232/ && cd ../jnode-assembly/target
        
        # Create artifact with H2 1.4.200
        cp -r ../../temp-lib ../../artifacts/lib-h2-1.4.200
        rm -f ../../artifacts/lib-h2-1.4.200/h2-*.jar
        cp ../../jdbc-drivers/old-drivers/h2-1.4.200.jar ../../artifacts/lib-h2-1.4.200/ 2>/dev/null || echo "H2 1.4.200 not found"
        cd ../../artifacts && tar -czf jnode-lib-h2-1.4.200.tar.gz lib-h2-1.4.200/ && cd ../jnode-assembly/target
        
        # Create artifact with H2 1.3.174
        cp -r ../../temp-lib ../../artifacts/lib-h2-1.3.174
        rm -f ../../artifacts/lib-h2-1.3.174/h2-*.jar
        cp ../../jdbc-drivers/old-drivers/h2-1.3.174.jar ../../artifacts/lib-h2-1.3.174/
        cd ../../artifacts && tar -czf jnode-lib-h2-1.3.174.tar.gz lib-h2-1.3.174/ && cd ../jnode-assembly/target
        
        # Also keep the full distribution
        cp jnode-*.zip ../../artifacts/jnode-full-distribution.zip
        
        cd ../../artifacts
        echo "Created artifacts:"
        ls -la
        
    - name: Upload artifacts for download
      uses: actions/upload-artifact@v4
      with:
        name: jnode-deployment-artifacts
        path: artifacts/
        retention-days: 30
        
    - name: Create GitHub Release
      if: ${{ github.event.inputs.create_release == 'true' && github.event.inputs.release_tag != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        name: JNode ${{ github.event.inputs.release_tag }}
        files: |
          artifacts/jnode-lib-h2-*.tar.gz
          artifacts/jnode-full-distribution.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}