name: Release Build

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Build all distribution archives
      run: mvn clean package -P all
      
    - name: Build stable distribution archives
      run: mvn clean package -P stable
      
    - name: Create release archives with version
      run: |
        cd jnode-assembly/target
        # Only process .zip files since assembly descriptors only create zip format
        for file in jnode-*.zip; do
          if [[ $file != *"${{ steps.version.outputs.VERSION }}"* ]]; then
            mv "$file" "jnode-${{ steps.version.outputs.VERSION }}-${file#jnode-}"
          fi
        done
        ls -la
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          jnode-assembly/target/jnode-*.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}